### ISSUE TITLE
findOptimalInchi Error 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#87]
```Python
 def test_ecoli_vmh_chebi(self):
        # load the e.coli core model and bulk annotate the metabolites. Check if any annoation tkes place (Chebi should cover all metabolites)
        mod_path = self.dat.joinpath("e_coli_vmh.xml")
        mod = MeMoModel.fromPath(mod_path)
        exp = AnnotationResult(999,999,999)
        res = AnnotationResult.fromTuple(annotateChEBI(mod.metabolites))
        add_test_case_to_table(self.test_ecoli_vmh_chebi.__name__, res, exp)   
        self.assertLessEqual(exp, res, msg=f"Expected amount of annotated metabolites: {exp}, calculated amount of annotated metabolites: {res}. All three must be >=")
 ```
 
 results in 
 
 ```
======================================================================
ERROR: test_ecoli_vmh_bigg_id_chebi (__main__.Test_annotateBulkRoutines.test_ecoli_vmh_bigg_id_chebi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/td/Projects/MeMoMe/tests/test_bulkPerformance.py", line 108, in test_ecoli_vmh_bigg_id_chebi
    res2 = AnnotationResult.fromTuple(annotateChEBI(mod.metabolites))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/td/Projects/MeMoMe/src/annotateChEBI.py", line 40, in annotateChEBI
    inchi = findOptimalInchi(inchis)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/td/Projects/MeMoMe/src/annotateInchiRoutines.py", line 69, in findOptimalInchi
    max_match = max(matches)
                ^^^^^^^^^^^^
ValueError: max() iterable argument is empty

```

**Comment by Porthmeus** [comment]
Should be fixed with #90

**Comment by Unaimend** [comment]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/d2a9556b-b554-4ab3-ba4c-68f1320f4d12)

Still there

**Comment by Unaimend** [comment]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/3453337c-5f00-46ec-a72e-39ad6b3ee23f)

Also fails

**Comment by Unaimend** [comment]
problem is here if inchi_string is empty 
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/2f9a7f65-eaf0-44b7-af5a-e3dda4d42c42)

![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/ac8112e5-dd38-4a10-be12-1966598df12b)

**Comment by Unaimend** [comment]
You only test if the string is != None, it probably also should no be empty. We should investigate why that happens

**Comment by Unaimend** [comment]
## ChEBI
['InChI=1S/C5H13NO4S/c1-6(2,3)4-5-10-11(7,8)9/h4-5H2,1-3H3', 'InChI=1S/C5H13NO4S/c1-6(2,3)4-5-10-11(7,8)9/h4-5H2,1-3H3/p+1'] as input for 
findOptimalInchi
